version: '3.1'

volumes:
    uploads: {}
    db: {}
    src: {}
    sessions: {}

services:
    mongo:
        image: mongo
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        depends_on:
            - mongo
        ports:
            - "8081:8081"

    # Hack for Windows not triggering inotify
    sync:
        build: docker/sync
        restart: unless-stopped
        volumes:
            - ./src:/dev/src/:consistent
            - src:/app/src

    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        environment:
            - BASEPATH
            - NODE_ENV
            - SMTP.host
            - SMTP.port
            - SMTP.user
            - SMTP.pass
            - SMTP.email
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
            - "10000:10000"
        volumes:
            - uploads:/app/uploads
            - src:/app/src
            - sessions:/app/sessions
            - ./static:/app/static/:ro
